### ISSUE TITLE
Please provide a way to get matched/found rows for UPDATE queries

### ISSUE THREAD

**Issue by jeremyevans** [github/trilogy#71]
I recently added a Sequel adapter for trilogy: https://github.com/jeremyevans/sequel/commit/0701217d80244a71db573455b8ec1ec4c287f3c3. I found trilogy very easy to use and that made the adapter quite easy to create.  Thank you for that!

One issue I ran into is that trilogy does not return the number of matched rows in an update statement, it returns the number of rows modified.  For example:

```ruby
c = Trilogy.new(...)
c.query('CREATE TABLE t(a integer)')
c.query('INSERT INTO t VALUES (1)')
c.query('UPDATE t SET a = 1').affected_rows
# => 0 # instead of 1
```

I think this is MySQL default behavior, so it seems reasonable, but most other databases do not operate this way, instead returning the number of matched rows.  It there a way to get the above code to return `1`?  The mysql2 gem supports this using `flags: Mysql2::Client::FOUND_ROWS` (which looks like it comes from `CLIENT_FOUND_ROWS` in the mysql driver).  If there is not currently a way, could support be added for it?

This affects Sequel because by default, Sequel checks during model instance updates that one row was updated.  If zero rows were updated, that by default indicates to Sequel that the underlying database record was already deleted, in which case Sequel should raise an exception.  I disabled that part in Sequel when trilogy is used, but it would be nice to be able to enable it.

There are a few other parts of Sequel that don't work perfectly with trilogy, but those are also issues with mysql2, or deliberately unsupported by trilogy (lack of application_timezone).

**Comment by composerinteralia** [comment]
Based on https://github.com/github/trilogy/blob/7ceee303b7d440f0b26cba65d00032bfb897c0ef/inc/trilogy/protocol.h#L20-L33 and https://github.com/github/trilogy/blob/7ceee303b7d440f0b26cba65d00032bfb897c0ef/contrib/ruby/ext/trilogy-ruby/cext.c#L454-L456, I think we might already have that by passing `found_rows` on connect: `Trilogy.new(found_rows: false`. Is that sufficient?

**Comment by jeremyevans** [comment]
That works, thank you very much!  Sorry I couldn't find it.  I'll update the Sequel trilogy driver to use that.

**Comment by jeremyevans** [comment]
Here's the change to Sequel: https://github.com/jeremyevans/sequel/commit/41e621fe1051441cf61d009bb76e3f7f7411f3b8
